bin/main.out : CPP/PE_74.cpp CPP/FactorialDigitSumChainCounter.h CPP/FactorialDigitSumChainCounter.cpp
	g++ -std=c++17 -Wall -W -O3 CPP/PE_74.cpp CPP/FactorialDigitSumChainCounter.cpp -o bin/main.out

.PHONY : clean
clean :
	rm bin/main.out

