/*
Pentagonal numbers are generated by the formula, Pn=n(3n − 1) / 2.

The first ten pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

NOTE: Solution = 5482660
*/

#include <cmath>

#include <iostream>

inline int pentagon(int n) { return n * (3 * n - 1) / 2; }

bool is_pentagon(int n) {
    int test_root = static_cast<int>(1 + sqrt(1 + 24 * n) / 6);
    return pentagon(test_root) == n;
}

bool check_sum_and_difference_are_pentagonal(int k, int j) {
    return is_pentagon(pentagon(k) + pentagon(j)) && is_pentagon(pentagon(k) - pentagon(j));
}

int minimise_pentagonal_difference(int k = 2) {
    int j = k - 1;
    do {
        if (check_sum_and_difference_are_pentagonal(k, j))
            return pentagon(k) - pentagon(j);
    } while (--j > 0);

    return minimise_pentagonal_difference(k + 1);
}

int main() {
    std::cout << minimise_pentagonal_difference() << std::endl;
}

