TestCombinations.out : ./TestCombinations.cpp ../include/utilities.h
	g++ -std=c++11 -Wall -W -lgmock -lgmock_main -lgtest -lgtest_main ./TestCombinations.cpp -o ./TestCombinations.out

TestTotient.out : ./TestTotient.cpp ../include/utilities.h
	g++ -std=c++11 -Wall -W -lgmock -lgmock_main -lgtest -lgtest_main ./TestTotient.cpp -o ./TestTotient.out

clean :
	rm ./test.out

