bin/main.out : PE_69.cpp
	g++ -std=c++11 -Wall -W -I/Users/neilmarshall/Documents/Programming/Project_Euler/utilities/include -L/Users/neilmarshall/Documents/Programming/Project_Euler/utilities/lib -lutilities PE_69.cpp -o bin/main.out

.PHONY : clean
clean :
	rm bin/main.out

